project:
  type: website
  preview:
    port: 4201

website:
  title: "DKU Wiki"
  navbar:
    left:
      - href: index.md
        text: About
      - href: articles/dining.md
        text: Dining
      - href: articles/e-commerce.md
        text: E-commerce
      - href: articles/travel.md
        text: Travel

format:
  html:
    mainfont: Helvetica
    monofont: JetBrains Mono
    email-obfuscation: javascript
    theme:
      light: flatly
      dark: darkly
    respect-user-color-scheme: true
    css: styles.css
    toc: true
